# Generated by Django 4.1.4 on 2022-12-11 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usertype', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'app_courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('academic_level', models.CharField(max_length=200)),
                ('academic_status', models.CharField(max_length=100)),
                ('academic_org', models.CharField(max_length=200)),
                ('academic_score', models.CharField(blank=True, max_length=200, null=True)),
                ('intake', models.CharField(blank=True, max_length=200, null=True)),
                ('shift', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(max_length=200)),
                ('visited_at', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 59, 44, 655880))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ses.course')),
            ],
            options={
                'db_table': 'app_students',
            },
        ),
    ]
